# Generated by Django 5.2.10 on 2026-02-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
