# Generated by Django 5.2.11 on 2026-02-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_token_id'),
        ('user', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_codes', to='account.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_access', to='user.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_guest_access', to='account.user')),
            ],
            options={
                'unique_together': {('event', 'vendor')},
            },
        ),
    ]
