# Generated by Django 5.2.11 on 2026-03-03 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_eventguestaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_photos', 'New Photos'), ('event_update', 'Event Update'), ('other', 'Other')], default='other', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.eventguestaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_photos', models.BooleanField(default=True)),
                ('notify_event_updates', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='user.eventguestaccess')),
            ],
        ),
    ]
