# Generated by Django 5.2.11 on 2026-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_guest_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventguestaccess',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
